name: Create Cypress report
on:
  push:
    branches:
      - 'main'

jobs:
  
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-20.04
    container: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - uses: actions/checkout@v2
      
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
      
      - name: Run Cypress tests
        run: npm run test:e2e
        continue-on-error: true
